title: ellieborden.tech
author: Ellie Borden
email: ellie91b@outlook.com
description: >-
  A collection of charcoal drawings by Ellie Borden.

social:
  twitter: 
  facebook: 
  instagram: ellie.borden
  github: ellieborden
  linkedin: bordenellie

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
