title: Ellie Borden
author: Ellie Borden
description: ellieborden.tech is my personal blog about software quality and testing. Its topics are primarily based on technical books and tend to emphasize theory and techniques rather than tools.

highlighter: null
permalink: /:title

url: https://ellieborden.tech
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
color_scheme: azul
