title: Ellie Borden
author: Ellie Borden
description: ellieborden.tech is a blog for software-testing professionals and enthusiasts. Its topics are based on technical books, industry trends, and my personal experiences.

highlighter: null
permalink: /:title

url: https://ellieborden.tech
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
color_scheme: azul
